#!/bin/sh

#Check if a template is mapped and if so, copy it in
if [ -r "/opt/DMRGateway.tmpl" ] 
then
	echo DMRGateway template file found - copying...
	cp -v /opt/DMRGateway.tmpl /opt/DMRGateway.ini
fi
#Check if a template is mapped and if so, copy it in
if [ -r "/opt/settings.tmpl" ] 
then
	echo Hytera settings template file found - copying...
	cp -v /opt/settings.tmpl /opt/settings.ini
fi

#Substitute enivronment variables into files


sed -i "s/{{callsign}}/$callsign/" /opt/settings.ini
sed -i "s/{{repeater_dmr_id}}/$repeater_dmr_id/" /opt/settings.ini
sed -i "s/{{color_code}}/$color_code/" /opt/settings.ini
sed -i "s/{{latitude)}/$latitude/" /opt/settings.ini
sed -i "s/{longitude}}/$longitude/" /opt/settings.ini
sed -i "s/{{antenna_height}}/$antenna_height/" /opt/settings.ini
sed -i "s/{{location}}/$location/" /opt/settings.ini
sed -i "s/{{description}}/$description/" /opt/settings.ini
sed -i "s/{{rx_freq}}/$rx_freq/" /opt/settings.ini
sed -i "s/{{tx_freq}}/$tx_freq/" /opt/settings.ini
sed -i "s/{{tx_power}}/$tx_power/" /opt/settings.ini
sed -i "s/{{timeslots}}/$timeslots/" /opt/settings.ini

sed -i "s/{{DMRG_OPTIONS}}/$DMRG_OPTIONS/" /opt/DMRGateway.ini
sed -i "s/{{DMRG_TARGET}}/$DMRG_TARGET/" /opt/DMRGateway.ini

#Add rewrite for TS1 TG9 is required
if [ "$DMRG_REWRITETS1TG9" != "" ]
then
	echo 'Setting TS1 rewrite 23590 <-> 9...' 
	sed -i "s/{{DMRG_REWRITETS1TG9}}/$DMRG_REWRITETS1TG9/" /opt/DMRGateway.ini
	sed -i "s/#TGRewrite=/TGRewrite=/" /opt/DMRGateway.ini
fi

#Disable dial a TG only on TS2 if required
if [ "$DMRG_DISABLEDIAL" == 1 ]
then
	echo 'Disable Dial-a-TG only on slot2...'
	sed -i "s/TypeRewrite=/#TypeRewrite/" /opt/DMRGateway.ini
fi


#Run processes

python /usr/local/bin/hytera-homebrew-bridge.py /opt/settings.ini &

cd /opt/DMRGateway

/opt/DMRGateway/DMRGateway /opt/DMRGateway.ini
	
