#!/bin/bash

#Check if a template is mapped and if so, copy it in
if [ -r "/opt/DMRGateway.tmpl" ] 
then
	echo DMRGateway template file found - copying...
	cp -v /opt/DMRGateway.tmpl /opt/DMRGateway.ini
fi
#Check if a template is mapped and if so, copy it in
if [ -r "/opt/settings.tmpl" ] 
then
	echo Hytera settings template file found - copying...
	cp -v /opt/settings.tmpl /opt/settings.ini
fi

#Substitute enivronment variables into files
sed -i "s/{{IPSC_MASTER_PEER}}/$IPSC_MASTER_PEER/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_MASTER_PEER}}/$IPSC_MASTER_PEER/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_MASTER_IP}}/$IPSC_MASTER_IP/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_MASTER_PORT}}/$IPSC_MASTER_PORT/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_MASTER_PEER}}/$IPSC_MASTER_PEER/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_TS1}}/$IPSC_TS1/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_TS2}}/$IPSC_TS2/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_RADIO_ID}}/$IPSC_RADIO_ID/" /opt/dmrlink.cfg
sed -i "s/{{IPSC_AUTH_KEY}}/$IPSC_AUTH_KEY/" /opt/dmrlink.cfg




sed -i "s/{{DMRG_OPTIONS}}/$DMRG_OPTIONS/" /opt/DMRGateway.ini
sed -i "s/{{DMRG_TARGET}}/$DMRG_TARGET/" /opt/DMRGateway.ini

#Add rewrite for TS1 TG9 is required
if [ "$DMRG_REWRITETS1TG9" != "" ]
then
	echo 'Setting TS1 rewrite 23590 <-> 9...' 
	sed -i "s/{{DMRG_REWRITETS1TG9}}/$DMRG_REWRITETS1TG9/" /opt/DMRGateway.ini
	sed -i "s/#TGRewrite=/TGRewrite=/" /opt/DMRGateway.ini
fi

#Disable dial a TG only on TS2 if required
if [ "$DMRG_DISABLEDIAL" == 1 ]
then
	echo 'Disable Dial-a-TG only on slot2...'
	sed -i "s/TypeRewrite=/#TypeRewrite/" /opt/DMRGateway.ini
fi


#Run processes


cd /opt/hytera

/opt/hytera/hytera-hombrew-bridge.py settings.ini

cd /opt/DMRGateway

/opt/DMRGateway/DMRGateway /opt/DMRGateway.ini
	
